version: '3'

volumes:
  db_value_production:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.10
    env_file:
      - ./.env
    volumes:
      - db_value_production:/var/lib/postgresql/data
 
  backend:
    image: rusmot/foodgram_backend
    env_file: 
      - ./.env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    image: rusmot/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
 
  gateway:
    image: nginx:1.19.3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/static
      - media_volume:/app/media 
    ports:
      - 9000:80